### ISSUE TITLE
【报错】启用插件失败

### ISSUE THREAD

**Issue by Agnes4m** [17TheWord/nonebot-plugin-warframe#2]
```
09-20 09:05:44 [ERROR] nonebot | Failed to import "nonebot_plugin_warframe"
Traceback (most recent call last):
  File "/home/unb/nb2/bot.py", line 29, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_warframe/__init__.py", line 5, in <module>
    from .data_source import chose_way
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_warframe/data_source.py", line 8
    match msg:
          ^
SyntaxError: invalid syntax
```

**Comment by 17TheWord** [comment]
`match` 语法在 `Python3.10` 中支持  
请更新 `Python` 版本 
或自行将 `match` 改为 `if elif`
